"""Add status column to tools

Revision ID: 6071336e6790
Revises: 7554153cf4a0
Create Date: 2025-12-30 18:21:39.531530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6071336e6790'
down_revision: Union[str, Sequence[str], None] = '7554153cf4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('status', sa.String(), nullable=True))
    op.add_column('tools', sa.Column('creator_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tools', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.drop_column('tools', 'creator_id')
    op.drop_column('tools', 'status')
    # ### end Alembic commands ###
